### ISSUE TITLE
Update Information Leakage check

### ISSUE THREAD

**Issue by shivankar-madaan** [taipan-scanner/Taipan#1]
When I ran taipan.exe for one of the domains
I got this result
`Security Issue: Information Leakage - Email = login-banner-1@2x.png,register-webinar@2x.png,splash-training@2x.png,sprinkler_drops@2x.png,watch-webinar@2x.png`

Can we have this updated if possible?
Thanks

**Comment by enkomio** [comment]
Yeah this is for sure a false positive. I'll add a check on the TLD.

**Comment by enkomio** [comment]
A check on the validity of the TLD was added. You can download a build release which resolve this problem from the artifact directory: https://ci.appveyor.com/project/enkomio/taipan/build/34/artifacts
