### ISSUE TITLE
visual studio 2017无法打开

### ISSUE THREAD

**Issue by xewn** [taipan-scanner/Taipan#3]
我下载了代码，用vs2017无法打开，应该是需要升级工程吧？我安装了F#的。

**Comment by enkomio** [comment]
Hi,
if google translate was correct, you question is:

> I downloaded the code, can not be opened with vs2017, it should be necessary to upgrade the project? I installed F#.

I recently switched to VS2017 and also the build will be based on VS2017 pretty soon. So, Could you please provide more info on which error are you seen? VS2017 should be able to open the project without any additional requirements.

**Comment by enkomio** [comment]
Hi,
just for your information the build https://ci.appveyor.com/project/enkomio/taipan/build/46/artifacts was done by considering VS2017.

**Comment by enkomio** [comment]
I have added a section in the documentation related to how to build Taipan.

**Comment by xewn** [comment]
thanks
